
import { DesktopAppDefinition } from './types';
import { Notepad } from '../../apps/notepad';
import { BlogApp } from '../../apps/BlogApp';
import { WikiApp } from '../../apps/wiki/WikiApp';
import { PicturesGallery } from '../../apps/pictureview/PicturesGallery';
import { Calculator } from '../../apps/calc/Calculator';
import { Paint } from '../../apps/paint/Paint';
import { ControlPanel } from '../../apps/ControlPanel';
import { AboutApp } from '../../apps/AboutApp';
import { CalendarApp } from '../../apps/calendar';
import { Terminal } from '../../apps/Terminal';
import { ProjectsGrid } from '../../apps/ProjectsGrid';
import { NewsApp } from './apps/news/NewsApp';
import { InternetExplorer } from '../../apps/internetexplorer/InternetExplorer';
import { OutlookExpress } from '../../apps/outlook/OutlookExpress';
import { WindowsMediaPlayer } from '../../apps/mediaplayer/WindowsMediaPlayer';
import { Minesweeper } from '../../apps/minesweeper';
import { ResumeApp } from './apps/resume/ResumeApp';

import { isFeatureEnabled } from '../../config/features';

export const appRegistry: Record<string, DesktopAppDefinition> = {
  'internet-explorer': {
    id: 'internet-explorer',
    title: {
      en: 'Internet Explorer',
      ru: 'Internet Explorer',
      fr: 'Internet Explorer',
      es: 'Internet Explorer',
      zh: 'Internet Explorer',
      ja: 'Internet Explorer',
      ko: 'Internet Explorer',
    },
    iconKey: 'internetExplorerIcon',
    component: InternetExplorer,
    defaultWindow: { width: 960, height: 640 },
    showInStartMenu: true,
  },
  'outlook': {
    id: 'outlook',
    title: {
      en: 'Outlook Express',
      ru: 'Outlook Express',
      fr: 'Outlook Express',
      es: 'Outlook Express',
      zh: 'Outlook Express',
      ja: 'Outlook Express',
      ko: 'Outlook Express',
    },
    iconKey: 'mailIcon',
    component: OutlookExpress,
    defaultWindow: { width: 860, height: 560 },
    showInStartMenu: true,
  },
  'windows-media-player': {
    id: 'windows-media-player',
    title: {
      en: 'Windows Media Player',
      ru: 'Windows Media Player',
      fr: 'Windows Media Player',
      es: 'Windows Media Player',
      zh: 'Windows Media Player',
      ja: 'Windows Media Player',
      ko: 'Windows Media Player',
    },
    iconKey: 'mediaPlayerIcon',
    component: WindowsMediaPlayer,
    defaultWindow: { width: 400, height: 580, resizable: false },
    showInStartMenu: true,
  },
  'projects-grid': {
    id: 'projects-grid',
    title: {
      en: 'My Projects',
      ru: 'Мои Проекты',
      fr: 'Mes Projets',
      es: 'Mis Proyectos',
      zh: '我的项目',
      ja: 'マイプロジェクト',
      ko: '내 프로젝트',
    },
    iconKey: 'projectsIcon',
    component: ProjectsGrid,
    defaultWindow: { width: 820, height: 560 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'calculator': {
    id: 'calculator',
    title: {
      en: 'Calculator',
      ru: 'Калькулятор',
      fr: 'Calculatrice',
      es: 'Calculadora',
      zh: '计算器',
      ja: '电卓',
      ko: '계산기',
    },
    iconKey: 'calculatorIcon',
    component: Calculator,
    defaultWindow: { width: 320, height: 400, resizable: false },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'paint': {
    id: 'paint',
    title: {
      en: 'Paint',
      ru: 'Paint',
      fr: 'Paint',
      es: 'Paint',
      zh: 'Paint',
      ja: 'Paint',
      ko: 'Paint',
    },
    iconKey: 'paintIcon',
    component: Paint,
    defaultWindow: { width: 900, height: 700 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'control-panel': {
    id: 'control-panel',
    title: {
      en: 'Control Panel',
      ru: 'Панель управления',
      fr: 'Panneau de configuration',
      es: 'Panel de control',
      zh: '控制面板',
      ja: 'コントロール パネル',
      ko: '제어판',
    },
    iconKey: 'controlPanelIcon',
    component: ControlPanel,
    defaultWindow: { width: 760, height: 600 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'pictures': {
    id: 'pictures',
    title: {
      en: 'My Pictures',
      ru: 'Мои изображения',
      fr: 'Mes images',
      es: 'Mis imágenes',
      zh: '我的图片',
      ja: 'マイ ピクチャ',
      ko: '내 그림',
    },
    iconKey: 'folderIcon',
    component: PicturesGallery,
    defaultWindow: { width: 960, height: 620 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'content-reader': {
    id: 'content-reader',
    title: {
      en: 'Content Reader',
      ru: 'Просмотр контента',
      fr: 'Lecteur de contenu',
      es: 'Lector de contenido',
      zh: '内容阅读器',
      ja: 'コンテンツ リーダー',
      ko: '콘텐츠 리더',
    },
    iconKey: 'richTextIcon',
    component: BlogApp,
    defaultWindow: { width: 960, height: 640 },
    showInStartMenu: false,
    showOnDesktop: false,
  },
  'blog': {
    id: 'blog',
    title: {
      en: 'Blog',
      ru: 'Блог',
      fr: 'Blog',
      es: 'Blog',
      zh: '博客',
      ja: 'ブログ',
      ko: '블로그',
    },
    iconKey: 'richTextIcon', // textDocumentIcon in Desktop.tsx
    component: BlogApp,
    defaultWindow: { width: 960, height: 640 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'news': {
    id: 'news',
    title: {
      en: 'News',
      ru: 'Новости',
      fr: 'Actualités',
      es: 'Noticias',
      zh: '新闻',
      ja: 'ニュース',
      ko: '뉴스',
    },
    iconKey: 'newsIcon',
    component: NewsApp,
    defaultWindow: { width: 900, height: 600 },
    showInStartMenu: isFeatureEnabled('news'),
    showOnDesktop: isFeatureEnabled('news'),
  },
  'wiki': {
    id: 'wiki',
    title: {
      en: 'Wiki',
      ru: 'Вики',
      fr: 'Wiki',
      es: 'Wiki',
      zh: '维基',
      ja: 'ウィキ',
      ko: '위키',
    },
    iconKey: 'folderIcon',
    component: WikiApp,
    defaultWindow: { width: 960, height: 640 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'notepad': {
    id: 'notepad',
    title: {
      en: 'Notepad',
      ru: 'Блокнот',
      fr: 'Bloc-notes',
      es: 'Bloc de notas',
      zh: '记事本',
      ja: 'メモ帳',
      ko: '메모장',
    },
    iconKey: 'notepadIcon',
    component: Notepad,
    defaultWindow: { width: 640, height: 480 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'calendar': {
    id: 'calendar',
    title: {
      en: 'Calendar',
      ru: 'Календарь',
      fr: 'Calendrier',
      es: 'Calendario',
      zh: '日历',
      ja: 'カレンダー',
      ko: '달력',
    },
    iconKey: 'calendarIcon',
    component: CalendarApp,
    defaultWindow: { width: 840, height: 600 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'terminal': {
    id: 'terminal',
    title: {
      en: 'Terminal',
      ru: 'Терминал',
      fr: 'Terminal',
      es: 'Terminal',
      zh: '终端',
      ja: 'ターミナル',
      ko: '터미널',
    },
    iconKey: 'terminalIcon',
    component: Terminal,
    defaultWindow: { width: 760, height: 480 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'task-manager': {
    id: 'task-manager',
    title: {
      en: 'Task Manager',
      ru: 'Диспетчер задач',
      fr: 'Gestionnaire des tâches',
      es: 'Administrador de tareas',
      zh: '任务管理器',
      ja: 'タスク マネージャー',
      ko: '작업 관리자',
    },
    iconKey: 'controlPanelIcon',
    component: ControlPanel, // Custom launch logic in Desktop.tsx
    defaultWindow: { width: 600, height: 500 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'about': {
    id: 'about',
    title: {
      en: 'About Me',
      ru: 'Обо мне',
      fr: 'À propos',
      es: 'Sobre mí',
      zh: '关于我',
      ja: '私について',
      ko: '소개',
    },
    iconKey: 'folderIcon',
    component: AboutApp,
    defaultWindow: { width: 720, height: 520 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'minesweeper': {
    id: 'minesweeper',
    title: {
      en: 'Minesweeper',
      ru: 'Сапер',
      fr: 'Démineur',
      es: 'Buscaminas',
      zh: '扫雷',
      ja: 'マインスイーパ',
      ko: '지뢰찾기',
    },
    iconKey: 'minesweeperIcon',
    component: Minesweeper,
    defaultWindow: { width: 360, height: 480, resizable: false },
    showInStartMenu: true,
    showOnDesktop: true,
  },
  'my-cv': {
    id: 'my-cv',
    title: {
      en: 'My CV',
      ru: 'Моё резюме',
      fr: 'Mon CV',
      es: 'Mi CV',
      zh: '我的简历',
      ja: '私の履歴書',
      ko: '내 이력서',
    },
    iconKey: 'folderIcon',
    component: ResumeApp,
    defaultWindow: { width: 720, height: 560 },
    showInStartMenu: true,
    showOnDesktop: true,
  },
};
